### ISSUE TITLE
Error when attempting to run

### ISSUE THREAD

**Issue by bmp412** [ElTav/AmexOffers#1]
Not quite sure what the issue is. Selenium & chromedriver appear to be fine. Is something missing from the readme or is my environment off in some way? Help appreciated.

Log:
```
C:\Users\User\AppData\Local\Programs\Python\Python37>python AmexOffers.py
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "AmexOffers.py", line 241, in <module>
    main()
  File "AmexOffers.py", line 199, in main
    driver = get_driver()
  File "AmexOffers.py", line 59, in get_driver
    return webdriver.Chrome(executable_path=driver_path, options=options)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.windows' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

```

**Comment by bmp412** [comment]
Just hard coded return webdriver.Chrome() to my path
