### ISSUE TITLE
Not logging in with new AmEx site

### ISSUE THREAD

**Issue by by3times1minus1** [ElTav/AmexOffers#6]
I'm not sure if this is project still supported?  Getting the error message "Ran into error waiting for the login form to load".  Assuming AmEx has changed their interfact in the past 2 years since this was updated.
Traceback (most recent call last):
  File "/Users/.../AmexOffers.py", line 273, in <module>
    main()
  File "/Users/...AmexOffers.py", line 238, in main
    open_card_stack(driver, initial_open=True)
  File "/Users/.../AmexOffers.py", line 68, in open_card_stack
    EC.element_to_be_clickable((By.CSS_SELECTOR, card_stack_css))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by ElTav** [comment]
Hey, unfortunately, I'm no longer officially supporting this but would be more than happy to approve a PR if you manage to get it working. I'm guessing they just changed the css so should be relatively straightforward to do
